spring:
  datasource:
    url: jdbc:mysql://42.55.22.222:3306/test?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: a3EljBT8vhAlvdTG332wQaiz6/5yMFdLYa8tN2T332RAC1/PMpTG08lA5tsdelqk7HNze3sbermWOeaSuZaQ==
public-key: MFwwDQYJKoZIhsscNAQE223ADSwAwSAJBAKdZMH5HZddUV0YXddXmszUDZaxUr33QlLwbgzess2wFoVB/kN02zdssLGG8MH6k8883jALuOeJpaKVp5/SUCAwEAAQ==
