spring:
  datasource:
    url: jdbc:mysql://192.168.1.252:3306/test?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123
#aluser:
#  tx-group:
#  accessKey:
#  secretKey: